- name: Deploy GJP Developer Web React App to Ubuntu Server & restart Nginx
  hosts: all
  become: yes
      
  tasks:
    - name: Create gjp-developer directory
      file:
        path: /var/www/gjp/developer  # Change this path to your desired directory
        state: directory
        mode: '0755'

    - name: Upload build to /var/www/gjp/developer
      copy:
        src: "../../../../gjp-open/gjp-open-developer-web-react/dist/"
        dest: "/var/www/gjp/developer"
        mode: 0755
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted