- name: Deploy GJP Blog Web React App to Ubuntu Server & restart Nginx
  hosts: all
  become: yes
      
  tasks:
    - name: Create gjp-blog directory
      file:
        path: /var/www/gjp/blog  # Change this path to your desired directory
        state: directory
        mode: '0755'

    - name: Upload build to /var/www/gjp/blog
      copy:
        src: "../../../../gjp-open/gjp-open-blog-web-react/dist/"
        dest: "/var/www/gjp/blog"
        mode: 0755
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted